//! The step-assignment table: which phase step each planner op lands in, and
//! whether the target dialect can run it with its native statement.
//!
//! ```text
//! class Author(Model):              ferro migrate new author_bio
//!     bio: str | None = None   ──▶  AddColumn  author.bio  → schema, native
//!     name: str                ──▶  AddColumn  author.name → expand, backfill, contract
//!     age: str  # was int      ──▶  AlterColumnType on SQLite → schema, a table rebuild
//! ```
//!
//! [`assign`] is the one decision every generator ticket fills in per
//! direction and dialect: the plain `ALTER TABLE` edits of an existing table
//! (add and drop a column, a Postgres type change and nullability relaxation,
//! a Postgres foreign key or check staged `NOT VALID` ([`stages_constraints`])),
//! an index step for each index change ([`is_index_step`]), SQLite's table
//! rebuilds (whose native-or-rebuild table is
//! [`super::rebuild::needs_rebuild`]), and every shape it cannot render yet
//! answered with the ticket that will. It decides where an op goes, never
//! what it says: every statement still comes from [`crate::render_plan`] or
//! [`super::rebuild::render`] (AGENTS.md § I-1).

use super::rebuild;
use crate::emit::{column_riders, standalone_indexes};
use crate::{Dialect, MigrationOp};
use ferro_ddl_lowering::{ConstraintMode, ResolvedStorage, resolve_column_storage};
use ferro_schema_ir::{IrEnvelope, SchemaColumn, SchemaIrPayload, SchemaModel};

/// The phase step an op lands in, in the order a migration's steps run.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Phase {
    /// Label additions to enum types that already exist (ADR-0011, ADR-0041):
    /// first in the migration, so every later step may write the new label.
    Labels,
    /// The one atomic DDL step of a migration that needs no data step.
    Schema,
    /// Columns added nullable ahead of a backfill ([`super::backfill`]).
    Expand,
    /// A data step filling values existing rows lack.
    Backfill,
    /// One index built or dropped on an existing table (ticket #527).
    Index,
    /// Postgres staged `NOT NULL` checks installed `NOT VALID`.
    AddConstraint,
    /// Validation and `SET NOT NULL` after a backfill, and every destructive
    /// op of a migration with a data step ([`waits_for_the_data_steps`]).
    Contract,
    /// Validation of staged constraints with no contract (ticket #527).
    Validate,
}

impl Phase {
    /// The step's name after `NN_`.
    pub fn step_name(self) -> &'static str {
        match self {
            Phase::Labels => "labels",
            Phase::Schema => "schema",
            Phase::Expand => "expand",
            Phase::Backfill => "backfill",
            Phase::Index => "index",
            Phase::AddConstraint => "add_constraint",
            Phase::Contract => "contract",
            Phase::Validate => "validate",
        }
    }
}

/// Why the generator writes nothing for an op, when no rendering exists for
/// it yet or ever.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Refusal {
    /// Generated by a later ticket.
    Ticket(u32),
    /// The op changes a table's primary key: refused with the restructure
    /// recipe ([`super::GenerateError::PrimaryKeyChange`]).
    PrimaryKeyChange,
    /// The op moves `column` to or from a native Postgres enum type: refused
    /// with the add-copy-drop recipe ([`super::GenerateError::EnumTypeMove`]).
    EnumTypeMove {
        /// The column.
        column: String,
    },
    /// The op is planned only against a live database (an invalid index or
    /// a `NOT VALID` constraint), never between two declared snapshots.
    LiveOnly,
}

/// What it takes to run an op on the context's dialect.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Needs {
    /// The dialect's own statement, as [`crate::render_plan`] renders it.
    Native,
    /// A SQLite table rebuild ([`super::rebuild`]), in the same phase step.
    Rebuild,
    /// Values for existing rows ([`demands_values`]): the migration's
    /// expand → backfill → contract.
    Backfill,
    /// Not generated.
    Refused(Refusal),
}

/// Where one op goes and what running it needs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StepAssignment {
    /// The phase step the op lands in.
    pub phase: Phase,
    /// What it needs on the context's dialect.
    pub needs: Needs,
}

/// Which file of a step the op is rendered into.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlanDirection {
    /// The up file: parent snapshot → target modelset.
    Up,
    /// The down file: target modelset → parent snapshot.
    Down,
}

/// What [`assign`] reads beside the op: the dialect, which way the file
/// goes, and the op's table on either side of the file.
#[derive(Clone, Copy, Debug)]
pub struct PlanContext<'a> {
    /// The dialect the op is rendered for.
    pub dialect: Dialect,
    /// The op's table exists before the file runs.
    pub table_exists_before: bool,
    /// The op's table exists after the file runs.
    pub table_exists_after: bool,
    /// Which file the op is rendered into.
    pub direction: PlanDirection,
    /// The op's table as the file finds it.
    pub before: Option<&'a SchemaModel>,
    /// The op's table as the file leaves it.
    pub after: Option<&'a SchemaModel>,
    /// The migration has a data step after its schema step (a generated
    /// backfill or guard, or one a person added): its destructive ops wait
    /// for the contract ([`waits_for_the_data_steps`]).
    pub data_steps: bool,
}

impl<'a> PlanContext<'a> {
    /// The context of `op` in a file that turns `before` into `after`.
    pub fn of(
        op: &MigrationOp,
        before: &'a IrEnvelope<SchemaIrPayload>,
        after: &'a IrEnvelope<SchemaIrPayload>,
        dialect: Dialect,
        direction: PlanDirection,
    ) -> Self {
        let find = |ir: &'a IrEnvelope<SchemaIrPayload>| {
            let table = op.table()?;
            ir.payload
                .models
                .iter()
                .find(|model| model.table_name == table)
        };
        let (before, after) = (find(before), find(after));
        PlanContext {
            dialect,
            table_exists_before: before.is_some(),
            table_exists_after: after.is_some(),
            direction,
            before,
            after,
            data_steps: false,
        }
    }

    /// This context in a migration that has (`true`) or lacks a data step
    /// after its schema step.
    pub fn with_data_steps(self, data_steps: bool) -> Self {
        PlanContext { data_steps, ..self }
    }

    fn column_before(&self, name: &str) -> Option<&'a SchemaColumn> {
        column(self.before?, name)
    }

    fn column_after(&self, name: &str) -> Option<&'a SchemaColumn> {
        column(self.after?, name)
    }

    fn on_existing_table(&self) -> bool {
        self.table_exists_before && self.table_exists_after
    }
}

fn column<'a>(model: &'a SchemaModel, name: &str) -> Option<&'a SchemaColumn> {
    model.columns.iter().find(|col| col.name == name)
}

/// Whether existing rows need a value for `col` that no statement supplies:
/// it is `NOT NULL` and declares no default to backfill them with.
pub fn needs_values(col: &SchemaColumn) -> bool {
    !col.nullable && col.default.as_ref().is_none_or(serde_json::Value::is_null)
}

/// Whether `op`, in the file `ctx` describes, asks the rows its table already
/// holds for a value no statement can supply: in an up file, on a table that
/// exists before and after it, a new non-key column [`needs_values`] (A3,
/// A2b, C1 required), or a nullable column made `NOT NULL` (A7a). A property
/// of the models, never of the dialect: such an op is the migration's
/// expand → backfill → contract ([`super::backfill`]).
pub fn demands_values(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    if ctx.direction != PlanDirection::Up || !ctx.on_existing_table() {
        return false;
    }
    match op {
        MigrationOp::AddColumn { column, .. } => ctx
            .column_after(column)
            .is_some_and(|col| !col.primary_key && needs_values(col)),
        MigrationOp::AlterColumnNullability { column, .. } => matches!(
            (ctx.column_before(column), ctx.column_after(column)),
            (Some(old), Some(new))
                if old.nullable && !new.nullable && !old.primary_key && !new.primary_key
        ),
        _ => false,
    }
}

/// Whether `op`, in the file `ctx` describes, puts back a column the rows its
/// table already holds have no value for: in a down file, on a table that
/// exists before and after it, a re-added non-key column [`needs_values`]
/// (the down of A4's dropped required column). Nothing backfills it: the
/// generated down adds it nullable and sets it `NOT NULL` on Postgres, which
/// reaches the parent snapshot on an empty table and fails on a populated one
/// (ADR-0033); the Alembic bridge writes the plain op, marked
/// `data-dependent` (ADR-0041).
pub fn restores_values(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    if ctx.direction != PlanDirection::Down || !ctx.on_existing_table() {
        return false;
    }
    match op {
        MigrationOp::AddColumn { column, .. } => ctx
            .column_after(column)
            .is_some_and(|col| !col.primary_key && needs_values(col)),
        _ => false,
    }
}

/// Whether `col` is stored as a native Postgres enum type.
fn native_enum(col: &SchemaColumn) -> bool {
    matches!(
        resolve_column_storage(col, Dialect::Postgres),
        Ok(ResolvedStorage::PgEnum { .. })
    )
}

/// Whether `op` drops a CHECK or an index that goes with a column the same
/// file drops: the column check `ck_<table>_<col>` of a dropped column, or an
/// index over one. Postgres drops both with the column; SQLite drops a
/// column's own inline check with it.
pub fn goes_with_a_dropped_column(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    let (Some(before), Some(after)) = (ctx.before, ctx.after) else {
        return false;
    };
    let dropped = |name: &str| column(before, name).is_some() && column(after, name).is_none();
    match op {
        MigrationOp::DropCheck { name, .. } => before
            .checks
            .iter()
            .any(|check| &check.name == name && dropped(&check.column)),
        MigrationOp::DropIndex { name, .. } => standalone_indexes(before)
            .into_iter()
            .any(|(index, columns, _)| &index == name && columns.iter().any(|c| dropped(c))),
        _ => false,
    }
}

/// Whether the generator leaves `op` out of the file: on SQLite, the drop of
/// a dropped column's own inline check, which the `DROP COLUMN` already
/// removes (the renderer has no statement for it, only a warning that would
/// be false here).
pub fn carried_by_its_column_drop(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    ctx.dialect == Dialect::Sqlite
        && matches!(op, MigrationOp::DropCheck { .. })
        && goes_with_a_dropped_column(op, ctx)
}

/// Whether `op` puts back an index, a column check or a foreign key over a
/// column the same file adds: a down putting back a column the up dropped
/// together with them, which go back with the column, as they went. A rider
/// of the added column ([`column_riders`]) goes with it, and so does a
/// composite index over it, which a dropped column took with it.
fn goes_with_an_added_column(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    let (Some(before), Some(after)) = (ctx.before, ctx.after) else {
        return false;
    };
    let added = |name: &str| column(before, name).is_none() && column(after, name).is_some();
    let riders = || {
        after
            .columns
            .iter()
            .filter(|col| added(&col.name))
            .map(|col| column_riders(after, &col.name))
    };
    match op {
        MigrationOp::AddIndex { columns, .. } => columns.iter().any(|name| added(name)),
        MigrationOp::AddCheck { name, .. } => riders().any(|riders| riders.has_check(name)),
        MigrationOp::AddForeignKey { column, .. } => {
            riders().any(|riders| riders.foreign_key.is_some_and(|fk| &fk.column == column))
        }
        _ => false,
    }
}

/// Whether `op` waits for the contract step, after every data step, in the
/// migration `ctx` describes (ADR-0025): in a migration with a data step, an
/// up's op that drops data ([`super::downs::drops_data`]: a column, a table,
/// the enum type that follows them) and what goes with a dropped column, so
/// a data step still reads what the migration drops; in its down, the ops
/// that put them back. Removals that discard no data (a foreign key, a check,
/// an index, a relaxed `NOT NULL`) stay where they are, and a migration with
/// no data step keeps its drops in its one schema step.
pub fn waits_for_the_data_steps(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    if !ctx.data_steps {
        return false;
    }
    match ctx.direction {
        PlanDirection::Up => super::downs::drops_data(op) || goes_with_a_dropped_column(op, ctx),
        PlanDirection::Down => match op {
            MigrationOp::AddTable { .. } => !ctx.table_exists_before && ctx.table_exists_after,
            MigrationOp::CreateEnumType { .. } => true,
            MigrationOp::AddColumn { column, .. } => {
                ctx.on_existing_table() && ctx.column_before(column).is_none()
            }
            _ => goes_with_an_added_column(op, ctx),
        },
    }
}

/// Whether `op` builds or drops an index on a table that exists before and
/// after the file — its own index step on every dialect (ADR-0044) — rather
/// than riding the table's or the column's own statement in the schema step.
pub fn is_index_step(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    matches!(
        op,
        MigrationOp::AddIndex { .. }
            | MigrationOp::DropIndex { .. }
            | MigrationOp::RedefineIndex { .. }
    ) && ctx.on_existing_table()
        && !goes_with_a_dropped_column(op, ctx)
        && !(ctx.direction == PlanDirection::Down && goes_with_an_added_column(op, ctx))
}

/// Whether the file stages `op`'s foreign keys and checks: added `NOT VALID`
/// in its step and validated by a later one (ADR-0043). Every up file on
/// Postgres does for a table that already exists; a down never does (a down
/// restores its step's pre-state in that step), nor does SQLite, which has no
/// unvalidated constraint (a rebuild validates by copying).
pub fn stages_constraints(ctx: &PlanContext<'_>) -> bool {
    constraint_mode(ctx.dialect, ctx.direction) == ConstraintMode::NotValid
        && ctx.on_existing_table()
}

/// The mode a file going `direction` on `dialect` adds its foreign keys and
/// checks in: `NOT VALID` in every Postgres up file, where each one is on a
/// table that already exists (a new table's ride its `CREATE TABLE`), and
/// plain everywhere else ([`stages_constraints`]).
pub fn constraint_mode(dialect: Dialect, direction: PlanDirection) -> ConstraintMode {
    if dialect == Dialect::Postgres && direction == PlanDirection::Up {
        ConstraintMode::NotValid
    } else {
        ConstraintMode::Plain
    }
}

/// Which step `op` lands in and what it needs, for the file and dialect
/// `ctx` describes.
pub fn assign(op: &MigrationOp, ctx: &PlanContext<'_>) -> StepAssignment {
    // A down meets the removal of a label its up added: the `labels` step's
    // down answers it (Postgres cannot drop a label; it stays).
    let added_label_goes_back =
        ctx.direction == PlanDirection::Down && matches!(op, MigrationOp::RemoveEnumLabel { .. });
    let phase = if matches!(op, MigrationOp::AddEnumLabel { .. }) || added_label_goes_back {
        Phase::Labels
    } else if waits_for_the_data_steps(op, ctx) {
        Phase::Contract
    } else if is_index_step(op, ctx) {
        Phase::Index
    } else {
        Phase::Schema
    };
    StepAssignment {
        phase,
        needs: needs(op, ctx),
    }
}

fn needs(op: &MigrationOp, ctx: &PlanContext<'_>) -> Needs {
    let primary_key = Needs::Refused(Refusal::PrimaryKeyChange);
    // SQLite's native-or-rebuild decision is the one table in
    // [`rebuild::needs_rebuild`]; this match keeps the refusals that win over
    // it and Postgres's own staging.
    let rebuild = rebuild::needs_rebuild(op, ctx.direction, ctx);
    let native_or_rebuild = if rebuild {
        Needs::Rebuild
    } else {
        Needs::Native
    };
    match op {
        MigrationOp::AddTable { .. }
        | MigrationOp::DropTable { .. }
        | MigrationOp::CreateEnumType { .. }
        | MigrationOp::DropEnumType { .. } => Needs::Native,
        // A declared rename (ADR-0032): native on both dialects but a
        // constraint's, which SQLite renames by rebuilding the table.
        MigrationOp::RenameTable { .. }
        | MigrationOp::RenameColumn { .. }
        | MigrationOp::RenameIndex { .. }
        | MigrationOp::RenamePolicy { .. } => Needs::Native,
        MigrationOp::RenameConstraint { .. } => native_or_rebuild,
        // Its own `labels` step ([`assign`]); a down has nothing to reverse.
        MigrationOp::AddEnumLabel { .. } => Needs::Native,
        // A declared label rename and an inferred type rename (ADR-0032).
        MigrationOp::RenameEnumLabel { .. } | MigrationOp::RenameEnumType { .. } => Needs::Native,
        // D2: rows may hold the label — a backfill, then the contract's swap
        // ([`super::backfill`], [`super::enums::render_swap_type`]).
        // In a down, the removal of a label the up added: nothing to run.
        MigrationOp::RemoveEnumLabel { .. } if ctx.direction == PlanDirection::Down => {
            Needs::Native
        }
        MigrationOp::RemoveEnumLabel { .. } => Needs::Backfill,
        MigrationOp::ChangePrimaryKey { .. } => primary_key,
        MigrationOp::AddColumn { column, .. } => {
            let Some(col) = ctx.column_after(column) else {
                return Needs::Native;
            };
            if col.primary_key {
                primary_key
            } else if demands_values(op, ctx) {
                Needs::Backfill
            } else {
                // A down putting back a dropped `NOT NULL` column on Postgres:
                // added nullable then `SET NOT NULL`, which fails while the
                // table has rows (ADR-0033).
                native_or_rebuild
            }
        }
        MigrationOp::DropColumn { column, .. } => {
            if ctx.column_before(column).is_some_and(|col| col.primary_key) {
                primary_key
            } else {
                native_or_rebuild
            }
        }
        MigrationOp::AlterColumnType { column, .. } => {
            let (old, new) = (ctx.column_before(column), ctx.column_after(column));
            if old.is_some_and(|col| col.primary_key) || new.is_some_and(|col| col.primary_key) {
                primary_key
            } else if rebuild {
                Needs::Rebuild
            } else if old.is_some_and(native_enum) || new.is_some_and(native_enum) {
                // To, from or between native enum types: no statement
                // converts the column in place.
                Needs::Refused(Refusal::EnumTypeMove {
                    column: column.clone(),
                })
            } else {
                Needs::Native
            }
        }
        MigrationOp::AlterColumnNullability { column, .. } => {
            let (old, new) = (ctx.column_before(column), ctx.column_after(column));
            if old.is_some_and(|col| col.primary_key) || new.is_some_and(|col| col.primary_key) {
                primary_key
            } else if demands_values(op, ctx) {
                // A7a: values for the NULL rows first, then the contract
                // (ADR-0042 on Postgres; the contract's rebuild on SQLite).
                Needs::Backfill
            } else if rebuild {
                Needs::Rebuild
            } else {
                Needs::Native
            }
        }
        // On an existing table, its own index step ([`is_index_step`]): the
        // plain statement on SQLite, built concurrently on Postgres.
        // A redefinition is the index step's drop then build on both.
        MigrationOp::AddIndex { .. }
        | MigrationOp::DropIndex { .. }
        | MigrationOp::RedefineIndex { .. } => Needs::Native,
        MigrationOp::DropCheck { .. } if goes_with_a_dropped_column(op, ctx) => Needs::Native,
        // On Postgres a foreign key or check added to an existing table is
        // added `NOT VALID` and validated by a later step
        // ([`stages_constraints`], ADR-0043); its drop is the plain
        // `DROP CONSTRAINT`. SQLite rebuilds the table.
        MigrationOp::AddCheck { .. }
        | MigrationOp::RebuildCheck { .. }
        | MigrationOp::DropCheck { .. }
        | MigrationOp::AddForeignKey { .. }
        | MigrationOp::RebuildForeignKey { .. } => native_or_rebuild,
        MigrationOp::ValidateConstraint { .. } | MigrationOp::RebuildIndex { .. } => {
            Needs::Refused(Refusal::LiveOnly)
        }
        // Postgres-only; the planner plans none on SQLite ([`super::row_security`]).
        MigrationOp::AddRowPolicy { .. }
        | MigrationOp::RebuildRowPolicy { .. }
        | MigrationOp::DropRowPolicy { .. }
        | MigrationOp::EnableRowSecurity { .. }
        | MigrationOp::ForceRowSecurity { .. }
        | MigrationOp::DisableRowSecurity { .. }
        | MigrationOp::NoForceRowSecurity { .. } => Needs::Native,
    }
}

#[cfg(test)]
mod tests {
    use super::super::tests::{column, ir, model, pk};
    use super::*;
    use ferro_schema_ir::{SchemaCheck, SchemaForeignKey, SchemaIndex};

    const DIALECTS: [Dialect; 2] = [Dialect::Postgres, Dialect::Sqlite];
    const DIRECTIONS: [PlanDirection; 2] = [PlanDirection::Up, PlanDirection::Down];

    fn nullable(name: &str, logical_type: &str) -> SchemaColumn {
        SchemaColumn {
            nullable: true,
            ..column(name, logical_type)
        }
    }

    fn defaulted(name: &str) -> SchemaColumn {
        SchemaColumn {
            default: Some(serde_json::json!("free")),
            ..column(name, "string")
        }
    }

    fn author(extra: Vec<SchemaColumn>) -> SchemaModel {
        let mut columns = vec![pk(), column("name", "string")];
        columns.extend(extra);
        model("Author", columns)
    }

    fn with_fk(mut model: SchemaModel, col: &str) -> SchemaModel {
        model.foreign_keys.push(SchemaForeignKey {
            renamed_from: None,
            column: col.into(),
            to_table: "team".into(),
            to_column: "id".into(),
            on_delete: Some("CASCADE".into()),
            name: Some(format!("fk_author_{col}_team")),
        });
        model
    }

    fn needs_for(
        op: &MigrationOp,
        before: &SchemaModel,
        after: &SchemaModel,
        dialect: Dialect,
        direction: PlanDirection,
    ) -> Needs {
        assignment_for(op, before, after, dialect, direction).needs
    }

    fn assignment_for(
        op: &MigrationOp,
        before: &SchemaModel,
        after: &SchemaModel,
        dialect: Dialect,
        direction: PlanDirection,
    ) -> StepAssignment {
        let (before, after) = (ir(vec![before.clone()]), ir(vec![after.clone()]));
        let ctx = PlanContext::of(op, &before, &after, dialect, direction);
        let assignment = assign(op, &ctx);
        let indexed = matches!(
            op,
            MigrationOp::AddIndex { .. } | MigrationOp::DropIndex { .. }
        );
        if !indexed {
            assert_eq!(assignment.phase, Phase::Schema, "{op:?}");
        }
        assignment
    }

    fn add(column: &str) -> MigrationOp {
        MigrationOp::AddColumn {
            table: "author".into(),
            column: column.into(),
        }
    }

    fn drop(column: &str) -> MigrationOp {
        MigrationOp::DropColumn {
            table: "author".into(),
            column: column.into(),
        }
    }

    #[test]
    fn the_context_reads_the_ops_table_on_both_sides_of_the_file() {
        let op = MigrationOp::AddTable {
            table: "author".into(),
        };
        let (empty, with) = (ir(vec![]), ir(vec![author(vec![])]));
        let ctx = PlanContext::of(&op, &empty, &with, Dialect::Sqlite, PlanDirection::Up);
        assert!(!ctx.table_exists_before && ctx.table_exists_after);
        assert!(ctx.before.is_none() && ctx.after.is_some());
        let enum_op = MigrationOp::CreateEnumType {
            type_name: "status".into(),
            labels: vec![],
        };
        let ctx = PlanContext::of(&enum_op, &with, &with, Dialect::Postgres, PlanDirection::Up);
        assert!(!ctx.table_exists_before && !ctx.table_exists_after);
    }

    #[test]
    fn whole_tables_and_enum_types_are_native_everywhere() {
        let ops = [
            MigrationOp::AddTable {
                table: "author".into(),
            },
            MigrationOp::DropTable {
                table: "author".into(),
            },
            MigrationOp::CreateEnumType {
                type_name: "status".into(),
                labels: vec!["a".into()],
            },
            MigrationOp::DropEnumType {
                type_name: "status".into(),
            },
        ];
        for op in &ops {
            for dialect in DIALECTS {
                for direction in DIRECTIONS {
                    assert_eq!(
                        needs_for(op, &author(vec![]), &author(vec![]), dialect, direction),
                        Needs::Native,
                        "{op:?} {dialect:?} {direction:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn adding_a_column_by_shape_dialect_and_direction() {
        let before = author(vec![]);
        // (column, dialect, direction) → needs
        let cases: Vec<(SchemaColumn, bool, Dialect, PlanDirection, Needs)> = vec![
            // A1: an optional column, both dialects, both directions.
            (
                nullable("bio", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("bio", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("bio", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A1 with a foreign key: SQLite takes an inline REFERENCES.
            (
                nullable("team_id", "integer"),
                true,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("team_id", "integer"),
                true,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            // A2: a literal default backfills existing rows.
            (
                defaulted("tier"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                defaulted("tier"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                defaulted("tier"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A required FK column with a default: no REFERENCES on SQLite.
            (
                SchemaColumn {
                    default: Some(serde_json::json!(1)),
                    ..column("team_id", "integer")
                },
                true,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Rebuild,
            ),
            // A3: required, no default — a backfill going up, everywhere.
            (
                column("slug", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            (
                column("slug", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            // A down putting back a dropped NOT NULL column: Postgres adds it
            // and sets NOT NULL; SQLite needs a rebuild.
            (
                column("slug", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Down,
                Needs::Native,
            ),
            (
                column("slug", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Rebuild,
            ),
            // A null default is no default.
            (
                SchemaColumn {
                    default: Some(serde_json::Value::Null),
                    ..column("slug", "string")
                },
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            // A primary key added to an existing table.
            (
                SchemaColumn {
                    primary_key: true,
                    ..column("uid", "string")
                },
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Refused(Refusal::PrimaryKeyChange),
            ),
        ];
        for (col, fk, dialect, direction, expected) in cases {
            let name = col.name.clone();
            let mut after = author(vec![col]);
            if fk {
                after = with_fk(after, &name);
            }
            assert_eq!(
                needs_for(&add(&name), &before, &after, dialect, direction),
                expected,
                "{name} {dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn dropping_a_column_by_shape_dialect_and_direction() {
        let after = author(vec![]);
        for dialect in DIALECTS {
            for direction in DIRECTIONS {
                // A4: a plain column, nullable or not.
                for col in [nullable("bio", "string"), column("bio", "string")] {
                    assert_eq!(
                        needs_for(&drop("bio"), &author(vec![col]), &after, dialect, direction),
                        Needs::Native
                    );
                }
                assert_eq!(
                    needs_for(
                        &drop("id"),
                        &author(vec![]),
                        &model("Author", vec![column("name", "string")]),
                        dialect,
                        direction
                    ),
                    Needs::Refused(Refusal::PrimaryKeyChange)
                );
            }
        }
        // C2: an FK column. SQLite cannot drop a table-level FOREIGN KEY's
        // column in place, the shape every rebuild writes, so a down dropping
        // the column its up added rebuilds too.
        let before = with_fk(author(vec![nullable("team_id", "integer")]), "team_id");
        let expect = [
            (Dialect::Sqlite, PlanDirection::Up, Needs::Rebuild),
            (Dialect::Sqlite, PlanDirection::Down, Needs::Rebuild),
            (Dialect::Postgres, PlanDirection::Up, Needs::Native),
            (Dialect::Postgres, PlanDirection::Down, Needs::Native),
        ];
        for (dialect, direction, needs) in expect {
            assert_eq!(
                needs_for(&drop("team_id"), &before, &after, dialect, direction),
                needs,
                "{dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn a_drop_waits_for_the_contract_only_in_a_migration_with_a_data_step() {
        let mut with_bio = author(vec![SchemaColumn {
            index: true,
            ..nullable("bio", "string")
        }]);
        with_bio.checks.push(SchemaCheck {
            name: "ck_author_bio".into(),
            column: "bio".into(),
            values: vec!["'a'".into()],
        });
        with_bio.indexes.push(SchemaIndex {
            name: "idx_author_bio".into(),
            columns: vec!["bio".into()],
            unique: false,
        });
        let without = author(vec![]);
        let drop_index = MigrationOp::DropIndex {
            table: "author".into(),
            name: "idx_author_bio".into(),
        };
        let drop_check = MigrationOp::DropCheck {
            table: "author".into(),
            name: "ck_author_bio".into(),
        };
        let add_check = MigrationOp::AddCheck {
            table: "author".into(),
            name: "ck_author_bio".into(),
        };
        let (with_ir, without_ir) = (ir(vec![with_bio]), ir(vec![without]));
        let empty = ir(vec![]);
        // (op, before, after, direction): each a drop, or in a down what puts
        // one back.
        let cases = [
            (drop("bio"), &with_ir, &without_ir, PlanDirection::Up),
            (drop_index, &with_ir, &without_ir, PlanDirection::Up),
            (drop_check, &with_ir, &without_ir, PlanDirection::Up),
            (
                MigrationOp::DropTable {
                    table: "author".into(),
                },
                &with_ir,
                &empty,
                PlanDirection::Up,
            ),
            (
                MigrationOp::DropEnumType {
                    type_name: "status".into(),
                },
                &with_ir,
                &empty,
                PlanDirection::Up,
            ),
            (add("bio"), &without_ir, &with_ir, PlanDirection::Down),
            (add_check, &without_ir, &with_ir, PlanDirection::Down),
            (
                MigrationOp::AddTable {
                    table: "author".into(),
                },
                &empty,
                &with_ir,
                PlanDirection::Down,
            ),
        ];
        for (op, before, after, direction) in &cases {
            for dialect in DIALECTS {
                let ctx = PlanContext::of(op, before, after, dialect, *direction);
                assert_ne!(assign(op, &ctx).phase, Phase::Contract, "{op:?}");
                let ctx = ctx.with_data_steps(true);
                assert!(waits_for_the_data_steps(op, &ctx), "{op:?} {dialect:?}");
                assert_eq!(assign(op, &ctx).phase, Phase::Contract, "{op:?}");
            }
        }
        // What discards no data stays where it is: a check dropped from a
        // column that stays, a relaxed NOT NULL, a new column or table.
        let unchecked = ir(vec![author(vec![nullable("bio", "string")])]);
        let checked = {
            let mut model = author(vec![nullable("bio", "string")]);
            model.checks.push(SchemaCheck {
                name: "ck_author_bio".into(),
                column: "bio".into(),
                values: vec!["'a'".into()],
            });
            ir(vec![model])
        };
        let stays = [
            (
                MigrationOp::DropCheck {
                    table: "author".into(),
                    name: "ck_author_bio".into(),
                },
                &checked,
                &unchecked,
            ),
            (add("bio"), &without_ir, &with_ir),
            (
                MigrationOp::AddTable {
                    table: "author".into(),
                },
                &empty,
                &with_ir,
            ),
        ];
        for (op, before, after) in &stays {
            let ctx = PlanContext::of(op, before, after, Dialect::Postgres, PlanDirection::Up)
                .with_data_steps(true);
            assert!(!waits_for_the_data_steps(op, &ctx), "{op:?}");
        }
        let relax = MigrationOp::AlterColumnNullability {
            table: "author".into(),
            column: "name".into(),
        };
        let loose = ir(vec![model(
            "Author",
            vec![pk(), nullable("name", "string")],
        )]);
        let strict = ir(vec![author(vec![])]);
        let ctx = PlanContext::of(
            &relax,
            &strict,
            &loose,
            Dialect::Postgres,
            PlanDirection::Up,
        )
        .with_data_steps(true);
        assert!(!waits_for_the_data_steps(&relax, &ctx));
    }

    #[test]
    fn a_type_change_is_native_on_postgres_and_a_rebuild_on_sqlite() {
        let op = MigrationOp::AlterColumnType {
            table: "author".into(),
            column: "age".into(),
        };
        let before = author(vec![column("age", "integer")]);
        let after = author(vec![column("age", "string")]);
        for direction in DIRECTIONS {
            assert_eq!(
                needs_for(&op, &before, &after, Dialect::Postgres, direction),
                Needs::Native
            );
            assert_eq!(
                needs_for(&op, &before, &after, Dialect::Sqlite, direction),
                Needs::Rebuild
            );
        }
        // To or from a native enum type: refused with the recipe.
        let status = SchemaColumn {
            enum_values: Some(vec![serde_json::json!("a")]),
            enum_type_name: Some("status".into()),
            ..column("age", "string")
        };
        assert_eq!(
            needs_for(
                &op,
                &before,
                &author(vec![status]),
                Dialect::Postgres,
                PlanDirection::Up
            ),
            Needs::Refused(Refusal::EnumTypeMove {
                column: "age".into()
            })
        );
        // The primary key's type.
        let id_op = MigrationOp::AlterColumnType {
            table: "author".into(),
            column: "id".into(),
        };
        let uuid_pk = model(
            "Author",
            vec![
                SchemaColumn {
                    primary_key: true,
                    ..column("id", "uuid")
                },
                column("name", "string"),
            ],
        );
        for dialect in DIALECTS {
            assert_eq!(
                needs_for(
                    &id_op,
                    &author(vec![]),
                    &uuid_pk,
                    dialect,
                    PlanDirection::Up
                ),
                Needs::Refused(Refusal::PrimaryKeyChange)
            );
        }
    }

    #[test]
    fn relaxing_not_null_is_native_on_postgres_and_requiring_it_is_a_backfill() {
        let op = MigrationOp::AlterColumnNullability {
            table: "author".into(),
            column: "bio".into(),
        };
        let required = author(vec![column("bio", "string")]);
        let optional = author(vec![nullable("bio", "string")]);
        let cases = [
            // A7b, and its down's SET NOT NULL.
            (
                &required,
                &optional,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                &optional,
                &required,
                Dialect::Postgres,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A7a: values for the NULL rows first (ADR-0042).
            (
                &optional,
                &required,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            (
                &required,
                &optional,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Rebuild,
            ),
            (
                &optional,
                &required,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Rebuild,
            ),
            // On SQLite too: the backfill comes first, the contract rebuilds.
            (
                &optional,
                &required,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Backfill,
            ),
        ];
        for (before, after, dialect, direction, expected) in cases {
            assert_eq!(
                needs_for(&op, before, after, dialect, direction),
                expected,
                "{dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn an_index_on_an_existing_table_is_its_own_index_step_on_every_dialect() {
        let index = SchemaIndex {
            name: "idx_author_name_bio".into(),
            columns: vec!["name".into(), "bio".into()],
            unique: false,
        };
        let plain = author(vec![nullable("bio", "string")]);
        let indexed = SchemaModel {
            indexes: vec![index],
            ..plain.clone()
        };
        let add = MigrationOp::AddIndex {
            table: "author".into(),
            name: "idx_author_name_bio".into(),
            columns: vec!["name".into(), "bio".into()],
            unique: false,
        };
        let drop_index = MigrationOp::DropIndex {
            table: "author".into(),
            name: "idx_author_name_bio".into(),
        };
        for dialect in DIALECTS {
            for direction in DIRECTIONS {
                let expected = StepAssignment {
                    phase: Phase::Index,
                    needs: Needs::Native,
                };
                assert_eq!(
                    assignment_for(&add, &plain, &indexed, dialect, direction),
                    expected
                );
                assert_eq!(
                    assignment_for(&drop_index, &indexed, &plain, dialect, direction),
                    expected
                );
            }
        }
        // A down putting back a column the up dropped with its index puts the
        // index back with it, in the schema step; an up's new index over a
        // new column is still its own step.
        let without_bio = author(vec![]);
        let restore = assignment_for(
            &add,
            &without_bio,
            &indexed,
            Dialect::Postgres,
            PlanDirection::Down,
        );
        assert_eq!(restore.phase, Phase::Schema);
        let build = assignment_for(
            &add,
            &without_bio,
            &indexed,
            Dialect::Postgres,
            PlanDirection::Up,
        );
        assert_eq!(build.phase, Phase::Index);
        // On a table the same file creates or drops, the index rides the
        // table's own statement on every dialect.
        let (empty, with) = (ir(vec![]), ir(vec![indexed.clone()]));
        for dialect in DIALECTS {
            let created = PlanContext::of(&add, &empty, &with, dialect, PlanDirection::Up);
            assert!(!created.table_exists_before && created.table_exists_after);
            assert_eq!(assign(&add, &created).needs, Needs::Native);
            let dropped = PlanContext::of(&drop_index, &with, &empty, dialect, PlanDirection::Up);
            assert!(dropped.table_exists_before && !dropped.table_exists_after);
            assert_eq!(assign(&drop_index, &dropped).needs, Needs::Native);
        }
        // An index over a column the same file drops goes with the column.
        let without_bio = author(vec![]);
        let ctx_ir = (ir(vec![indexed.clone()]), ir(vec![without_bio]));
        let ctx = PlanContext::of(
            &drop_index,
            &ctx_ir.0,
            &ctx_ir.1,
            Dialect::Postgres,
            PlanDirection::Up,
        );
        assert!(goes_with_a_dropped_column(&drop_index, &ctx));
        assert_eq!(assign(&drop_index, &ctx).needs, Needs::Native);
        assert!(!carried_by_its_column_drop(&drop_index, &ctx));
    }

    #[test]
    fn a_dropped_columns_own_check_goes_with_it_and_any_other_check_change_is_native_on_postgres() {
        let check = SchemaCheck {
            name: "ck_author_tier".into(),
            column: "tier".into(),
            values: vec!["'free'".into()],
        };
        let checked = SchemaModel {
            checks: vec![check],
            ..author(vec![nullable("tier", "string")])
        };
        let drop_check = MigrationOp::DropCheck {
            table: "author".into(),
            name: "ck_author_tier".into(),
        };
        let (before, gone) = (ir(vec![checked.clone()]), ir(vec![author(vec![])]));
        for dialect in DIALECTS {
            let ctx = PlanContext::of(&drop_check, &before, &gone, dialect, PlanDirection::Up);
            assert_eq!(assign(&drop_check, &ctx).needs, Needs::Native);
            assert_eq!(
                carried_by_its_column_drop(&drop_check, &ctx),
                dialect == Dialect::Sqlite
            );
        }
        // The column stays and only its check goes: an A10 drop.
        let unchecked = author(vec![nullable("tier", "string")]);
        assert_eq!(
            needs_for(
                &drop_check,
                &checked,
                &unchecked,
                Dialect::Sqlite,
                PlanDirection::Up
            ),
            Needs::Rebuild
        );
        assert_eq!(
            needs_for(
                &drop_check,
                &checked,
                &unchecked,
                Dialect::Postgres,
                PlanDirection::Up
            ),
            Needs::Native
        );
        let staged = [
            MigrationOp::AddCheck {
                table: "author".into(),
                name: "ck_author_tier".into(),
            },
            MigrationOp::RebuildCheck {
                table: "author".into(),
                name: "ck_author_tier".into(),
            },
            MigrationOp::AddForeignKey {
                table: "author".into(),
                column: "tier".into(),
            },
            MigrationOp::RebuildForeignKey {
                table: "author".into(),
                column: "tier".into(),
                old_name: "fk".into(),
            },
        ];
        for op in &staged {
            for direction in DIRECTIONS {
                assert_eq!(
                    needs_for(op, &checked, &checked, Dialect::Sqlite, direction),
                    Needs::Rebuild
                );
                assert_eq!(
                    needs_for(op, &checked, &checked, Dialect::Postgres, direction),
                    Needs::Native
                );
            }
        }
    }

    #[test]
    fn enum_label_and_type_ops_have_their_steps_and_are_native_everywhere() {
        let a = author(vec![]);
        let (before, after) = (ir(vec![a.clone()]), ir(vec![a]));
        let label = MigrationOp::AddEnumLabel {
            type_name: "status".into(),
            label: "x".into(),
        };
        let renames = [
            MigrationOp::RenameEnumLabel {
                type_name: "status".into(),
                old: "x".into(),
                new: "y".into(),
                columns: vec![("author".into(), "status".into())],
            },
            MigrationOp::RenameEnumType {
                old: "status".into(),
                new: "state".into(),
            },
        ];
        for dialect in DIALECTS {
            for direction in DIRECTIONS {
                let ctx = PlanContext::of(&label, &before, &after, dialect, direction);
                assert_eq!(
                    assign(&label, &ctx),
                    StepAssignment {
                        phase: Phase::Labels,
                        needs: Needs::Native,
                    }
                );
                for op in &renames {
                    let ctx = PlanContext::of(op, &before, &after, dialect, direction);
                    assert_eq!(
                        assign(op, &ctx),
                        StepAssignment {
                            phase: Phase::Schema,
                            needs: Needs::Native,
                        },
                        "{op:?}"
                    );
                }
            }
        }
        // The labels step runs first of every phase step.
        assert!(Phase::Labels < Phase::Schema);
        assert_eq!(Phase::Labels.step_name(), "labels");
    }

    #[test]
    fn row_security_ops_are_native_in_the_schema_step() {
        let a = author(vec![]);
        let table = || "author".to_string();
        let ops = [
            MigrationOp::AddRowPolicy {
                table: table(),
                name: "p".into(),
            },
            MigrationOp::RebuildRowPolicy {
                table: table(),
                name: "p".into(),
            },
            MigrationOp::DropRowPolicy {
                table: table(),
                name: "p".into(),
            },
            MigrationOp::EnableRowSecurity { table: table() },
            MigrationOp::ForceRowSecurity { table: table() },
            MigrationOp::DisableRowSecurity { table: table() },
            MigrationOp::NoForceRowSecurity { table: table() },
        ];
        for op in &ops {
            for direction in DIRECTIONS {
                assert_eq!(
                    assignment_for(op, &a, &a, Dialect::Postgres, direction),
                    StepAssignment {
                        phase: Phase::Schema,
                        needs: Needs::Native,
                    },
                    "{op:?}"
                );
            }
        }
    }

    #[test]
    fn live_only_ops_are_refused_naming_why() {
        let a = author(vec![]);
        let table = || "author".to_string();
        let cases = [
            (
                MigrationOp::ValidateConstraint {
                    table: table(),
                    name: "ck".into(),
                },
                Refusal::LiveOnly,
            ),
            (
                MigrationOp::RebuildIndex {
                    table: table(),
                    name: "idx".into(),
                    columns: vec![],
                    unique: false,
                },
                Refusal::LiveOnly,
            ),
        ];
        for (op, refusal) in cases {
            for dialect in DIALECTS {
                for direction in DIRECTIONS {
                    assert_eq!(
                        needs_for(&op, &a, &a, dialect, direction),
                        Needs::Refused(refusal.clone()),
                        "{op:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn a_primary_key_change_is_the_primary_key_refusal_everywhere() {
        let op = MigrationOp::ChangePrimaryKey {
            table: "author".into(),
            from: vec!["id".into()],
            to: vec!["name".into()],
        };
        let a = author(vec![]);
        for dialect in DIALECTS {
            for direction in DIRECTIONS {
                assert_eq!(
                    needs_for(&op, &a, &a, dialect, direction),
                    Needs::Refused(Refusal::PrimaryKeyChange)
                );
            }
        }
    }
}
