//! The step-assignment table: which phase step each planner op lands in, and
//! whether the target dialect can run it with its native statement.
//!
//! ```text
//! class Author(Model):              ferro migrate new author_bio
//!     bio: str | None = None   ──▶  AddColumn  author.bio  → schema, native
//!     name: str                ──▶  AddColumn  author.name → needs a backfill (ticket #534)
//!     age: str  # was int      ──▶  AlterColumnType on SQLite → needs a table rebuild (ticket #526)
//! ```
//!
//! [`assign`] is the one decision every generator ticket fills in per
//! direction and dialect: this slice renders the plain `ALTER TABLE` edits of
//! an existing table (add and drop a column, a Postgres type change and
//! nullability relaxation, SQLite indexes), and answers every shape it cannot
//! render yet with the ticket that will. It decides where an op goes, never
//! what it says: every statement still comes from [`crate::render_plan`]
//! (AGENTS.md § I-1).

use crate::emit::standalone_indexes;
use crate::{Dialect, MigrationOp};
use ferro_ddl_lowering::{ResolvedStorage, resolve_column_storage};
use ferro_schema_ir::{IrEnvelope, SchemaColumn, SchemaIrPayload, SchemaModel};

/// The phase step an op lands in, in the order a migration's steps run.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Phase {
    /// The one atomic DDL step of a migration that needs no data step.
    Schema,
    /// Columns added nullable ahead of a backfill (ticket #534).
    Expand,
    /// A data step filling values existing rows lack (ticket #534).
    Backfill,
    /// One index built or dropped on an existing table (ticket #527).
    Index,
    /// Postgres staged constraints installed `NOT VALID` (ticket #534).
    AddConstraint,
    /// Validation and `SET NOT NULL` after a backfill (ticket #534).
    Contract,
    /// Validation of staged constraints with no contract (ticket #527).
    Validate,
}

impl Phase {
    /// The step's name after `NN_`.
    pub fn step_name(self) -> &'static str {
        match self {
            Phase::Schema => "schema",
            Phase::Expand => "expand",
            Phase::Backfill => "backfill",
            Phase::Index => "index",
            Phase::AddConstraint => "add_constraint",
            Phase::Contract => "contract",
            Phase::Validate => "validate",
        }
    }
}

/// Why the generator writes nothing for an op, when no rendering exists for
/// it yet or ever.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Refusal {
    /// Generated by a later ticket.
    Ticket(u32),
    /// The op changes a table's primary key (ticket #536 owns the recipe).
    PrimaryKeyChange,
    /// The op is planned only against a live database (an invalid index or
    /// a `NOT VALID` constraint), never between two declared snapshots.
    LiveOnly,
}

/// What it takes to run an op on the context's dialect.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Needs {
    /// The dialect's own statement, as [`crate::render_plan`] renders it.
    Native,
    /// A SQLite table rebuild (ticket #526).
    Rebuild,
    /// Values for existing rows (ticket #534).
    Backfill,
    /// Not generated.
    Refused(Refusal),
}

/// Where one op goes and what running it needs.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StepAssignment {
    /// The phase step the op lands in.
    pub phase: Phase,
    /// What it needs on the context's dialect.
    pub needs: Needs,
}

/// Which file of a step the op is rendered into.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlanDirection {
    /// The up file: parent snapshot → target modelset.
    Up,
    /// The down file: target modelset → parent snapshot.
    Down,
}

/// What [`assign`] reads beside the op: the dialect, which way the file
/// goes, and the op's table on either side of the file.
#[derive(Clone, Copy, Debug)]
pub struct PlanContext<'a> {
    /// The dialect the op is rendered for.
    pub dialect: Dialect,
    /// The op's table exists before the file runs.
    pub table_exists_before: bool,
    /// The op's table exists after the file runs.
    pub table_exists_after: bool,
    /// Which file the op is rendered into.
    pub direction: PlanDirection,
    /// The op's table as the file finds it.
    pub before: Option<&'a SchemaModel>,
    /// The op's table as the file leaves it.
    pub after: Option<&'a SchemaModel>,
}

impl<'a> PlanContext<'a> {
    /// The context of `op` in a file that turns `before` into `after`.
    pub fn of(
        op: &MigrationOp,
        before: &'a IrEnvelope<SchemaIrPayload>,
        after: &'a IrEnvelope<SchemaIrPayload>,
        dialect: Dialect,
        direction: PlanDirection,
    ) -> Self {
        let find = |ir: &'a IrEnvelope<SchemaIrPayload>| {
            let table = op.table()?;
            ir.payload
                .models
                .iter()
                .find(|model| model.table_name == table)
        };
        let (before, after) = (find(before), find(after));
        PlanContext {
            dialect,
            table_exists_before: before.is_some(),
            table_exists_after: after.is_some(),
            direction,
            before,
            after,
        }
    }

    fn column_before(&self, name: &str) -> Option<&'a SchemaColumn> {
        column(self.before?, name)
    }

    fn column_after(&self, name: &str) -> Option<&'a SchemaColumn> {
        column(self.after?, name)
    }

    fn on_existing_table(&self) -> bool {
        self.table_exists_before && self.table_exists_after
    }
}

fn column<'a>(model: &'a SchemaModel, name: &str) -> Option<&'a SchemaColumn> {
    model.columns.iter().find(|col| col.name == name)
}

fn has_foreign_key(model: Option<&SchemaModel>, column: &str) -> bool {
    model.is_some_and(|model| model.foreign_keys.iter().any(|fk| fk.column == column))
}

/// Whether existing rows need a value for `col` that no statement supplies:
/// it is `NOT NULL` and declares no default to backfill them with.
pub fn needs_values(col: &SchemaColumn) -> bool {
    !col.nullable && col.default.as_ref().is_none_or(serde_json::Value::is_null)
}

/// Whether `col` is stored as a native Postgres enum type.
fn native_enum(col: &SchemaColumn) -> bool {
    matches!(
        resolve_column_storage(col, Dialect::Postgres),
        Ok(ResolvedStorage::PgEnum { .. })
    )
}

/// Whether `op` drops a CHECK or an index that goes with a column the same
/// file drops: the column check `ck_<table>_<col>` of a dropped column, or an
/// index over one. Postgres drops both with the column; SQLite drops a
/// column's own inline check with it.
pub fn goes_with_a_dropped_column(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    let (Some(before), Some(after)) = (ctx.before, ctx.after) else {
        return false;
    };
    let dropped = |name: &str| column(before, name).is_some() && column(after, name).is_none();
    match op {
        MigrationOp::DropCheck { name, .. } => before
            .checks
            .iter()
            .any(|check| &check.name == name && dropped(&check.column)),
        MigrationOp::DropIndex { name, .. } => standalone_indexes(before)
            .into_iter()
            .any(|(index, columns, _)| &index == name && columns.iter().any(|c| dropped(c))),
        _ => false,
    }
}

/// Whether the generator leaves `op` out of the file: on SQLite, the drop of
/// a dropped column's own inline check, which the `DROP COLUMN` already
/// removes (the renderer has no statement for it, only a warning that would
/// be false here).
pub fn carried_by_its_column_drop(op: &MigrationOp, ctx: &PlanContext<'_>) -> bool {
    ctx.dialect == Dialect::Sqlite
        && matches!(op, MigrationOp::DropCheck { .. })
        && goes_with_a_dropped_column(op, ctx)
}

/// Which step `op` lands in and what it needs, for the file and dialect
/// `ctx` describes.
pub fn assign(op: &MigrationOp, ctx: &PlanContext<'_>) -> StepAssignment {
    StepAssignment {
        phase: Phase::Schema,
        needs: needs(op, ctx),
    }
}

fn needs(op: &MigrationOp, ctx: &PlanContext<'_>) -> Needs {
    let sqlite = ctx.dialect == Dialect::Sqlite;
    let refused = |ticket| Needs::Refused(Refusal::Ticket(ticket));
    let primary_key = Needs::Refused(Refusal::PrimaryKeyChange);
    match op {
        MigrationOp::AddTable { .. }
        | MigrationOp::DropTable { .. }
        | MigrationOp::CreateEnumType { .. }
        | MigrationOp::DropEnumType { .. } => Needs::Native,
        // A label added to a type that already exists cannot be reversed by
        // a down (Postgres drops no enum label).
        MigrationOp::AddEnumLabel { .. } => refused(529),
        MigrationOp::AddColumn { column, .. } => {
            let Some(col) = ctx.column_after(column) else {
                return Needs::Native;
            };
            if col.primary_key {
                primary_key
            } else if needs_values(col) {
                match (ctx.direction, ctx.dialect) {
                    (PlanDirection::Up, _) => Needs::Backfill,
                    // A down putting back a dropped `NOT NULL` column: added
                    // nullable then `SET NOT NULL`, which fails while the
                    // table has rows (ADR-0033). SQLite has no `SET NOT NULL`.
                    (PlanDirection::Down, Dialect::Postgres) => Needs::Native,
                    (PlanDirection::Down, Dialect::Sqlite) => Needs::Rebuild,
                }
            } else if sqlite && !col.nullable && has_foreign_key(ctx.after, column) {
                // SQLite's ADD COLUMN takes REFERENCES only with a NULL
                // default; this column backfills a value.
                Needs::Rebuild
            } else {
                Needs::Native
            }
        }
        MigrationOp::DropColumn { column, .. } => {
            if ctx.column_before(column).is_some_and(|col| col.primary_key) {
                primary_key
            } else if sqlite
                && ctx.direction == PlanDirection::Up
                && has_foreign_key(ctx.before, column)
            {
                // SQLite refuses to drop a column a table-level FOREIGN KEY
                // names, the shape CREATE TABLE writes. A down drops the
                // column its own up added with an inline REFERENCES, which it
                // can.
                Needs::Rebuild
            } else {
                Needs::Native
            }
        }
        MigrationOp::AlterColumnType { column, .. } => {
            let (old, new) = (ctx.column_before(column), ctx.column_after(column));
            if old.is_some_and(|col| col.primary_key) || new.is_some_and(|col| col.primary_key) {
                primary_key
            } else if sqlite {
                Needs::Rebuild
            } else if old.is_some_and(native_enum) || new.is_some_and(native_enum) {
                refused(529)
            } else {
                Needs::Native
            }
        }
        MigrationOp::AlterColumnNullability { column, .. } => {
            let (old, new) = (ctx.column_before(column), ctx.column_after(column));
            if old.is_some_and(|col| col.primary_key) || new.is_some_and(|col| col.primary_key) {
                primary_key
            } else if sqlite {
                Needs::Rebuild
            } else if new.is_some_and(|col| !col.nullable) && ctx.direction == PlanDirection::Up {
                // ADR-0042: NOT NULL on Postgres is staged after a backfill.
                Needs::Backfill
            } else {
                Needs::Native
            }
        }
        MigrationOp::AddIndex { .. } | MigrationOp::DropIndex { .. } => {
            if sqlite || !ctx.on_existing_table() || goes_with_a_dropped_column(op, ctx) {
                Needs::Native
            } else {
                // An index on an existing Postgres table is its own
                // concurrent step (ADR-0044).
                refused(527)
            }
        }
        MigrationOp::DropCheck { .. } if goes_with_a_dropped_column(op, ctx) => Needs::Native,
        MigrationOp::AddCheck { .. }
        | MigrationOp::RebuildCheck { .. }
        | MigrationOp::DropCheck { .. }
        | MigrationOp::AddForeignKey { .. }
        | MigrationOp::RebuildForeignKey { .. } => {
            if sqlite {
                Needs::Rebuild
            } else {
                // Constraints on an existing Postgres table are staged
                // `NOT VALID` and validated (ADR-0043).
                refused(527)
            }
        }
        MigrationOp::ValidateConstraint { .. } | MigrationOp::RebuildIndex { .. } => {
            Needs::Refused(Refusal::LiveOnly)
        }
        MigrationOp::AddRowPolicy { .. }
        | MigrationOp::RebuildRowPolicy { .. }
        | MigrationOp::DropRowPolicy { .. }
        | MigrationOp::EnableRowSecurity { .. }
        | MigrationOp::ForceRowSecurity { .. }
        | MigrationOp::DisableRowSecurity { .. }
        | MigrationOp::NoForceRowSecurity { .. } => refused(531),
    }
}

/// The table whose primary key differs between `before` and `after`, if
/// any: the planner has no op for a key moving between columns, so the
/// generator reads it off the two snapshots.
pub fn primary_key_change(
    before: &IrEnvelope<SchemaIrPayload>,
    after: &IrEnvelope<SchemaIrPayload>,
) -> Option<String> {
    let key = |model: &SchemaModel| -> Vec<String> {
        model
            .columns
            .iter()
            .filter(|col| col.primary_key)
            .map(|col| col.name.clone())
            .collect()
    };
    before.payload.models.iter().find_map(|old| {
        let new = after
            .payload
            .models
            .iter()
            .find(|model| model.table_name == old.table_name)?;
        (key(old) != key(new)).then(|| old.table_name.clone())
    })
}

#[cfg(test)]
mod tests {
    use super::super::tests::{column, ir, model, pk};
    use super::*;
    use ferro_schema_ir::{SchemaCheck, SchemaForeignKey, SchemaIndex};

    const DIALECTS: [Dialect; 2] = [Dialect::Postgres, Dialect::Sqlite];
    const DIRECTIONS: [PlanDirection; 2] = [PlanDirection::Up, PlanDirection::Down];

    fn nullable(name: &str, logical_type: &str) -> SchemaColumn {
        SchemaColumn {
            nullable: true,
            ..column(name, logical_type)
        }
    }

    fn defaulted(name: &str) -> SchemaColumn {
        SchemaColumn {
            default: Some(serde_json::json!("free")),
            ..column(name, "string")
        }
    }

    fn author(extra: Vec<SchemaColumn>) -> SchemaModel {
        let mut columns = vec![pk(), column("name", "string")];
        columns.extend(extra);
        model("Author", columns)
    }

    fn with_fk(mut model: SchemaModel, col: &str) -> SchemaModel {
        model.foreign_keys.push(SchemaForeignKey {
            column: col.into(),
            to_table: "team".into(),
            to_column: "id".into(),
            on_delete: Some("CASCADE".into()),
            name: Some(format!("fk_author_{col}_team")),
        });
        model
    }

    fn needs_for(
        op: &MigrationOp,
        before: &SchemaModel,
        after: &SchemaModel,
        dialect: Dialect,
        direction: PlanDirection,
    ) -> Needs {
        let (before, after) = (ir(vec![before.clone()]), ir(vec![after.clone()]));
        let ctx = PlanContext::of(op, &before, &after, dialect, direction);
        let assignment = assign(op, &ctx);
        assert_eq!(assignment.phase, Phase::Schema);
        assignment.needs
    }

    fn add(column: &str) -> MigrationOp {
        MigrationOp::AddColumn {
            table: "author".into(),
            column: column.into(),
        }
    }

    fn drop(column: &str) -> MigrationOp {
        MigrationOp::DropColumn {
            table: "author".into(),
            column: column.into(),
        }
    }

    #[test]
    fn the_context_reads_the_ops_table_on_both_sides_of_the_file() {
        let op = MigrationOp::AddTable {
            table: "author".into(),
        };
        let (empty, with) = (ir(vec![]), ir(vec![author(vec![])]));
        let ctx = PlanContext::of(&op, &empty, &with, Dialect::Sqlite, PlanDirection::Up);
        assert!(!ctx.table_exists_before && ctx.table_exists_after);
        assert!(ctx.before.is_none() && ctx.after.is_some());
        let enum_op = MigrationOp::CreateEnumType {
            type_name: "status".into(),
            labels: vec![],
        };
        let ctx = PlanContext::of(&enum_op, &with, &with, Dialect::Postgres, PlanDirection::Up);
        assert!(!ctx.table_exists_before && !ctx.table_exists_after);
    }

    #[test]
    fn whole_tables_and_enum_types_are_native_everywhere() {
        let ops = [
            MigrationOp::AddTable {
                table: "author".into(),
            },
            MigrationOp::DropTable {
                table: "author".into(),
            },
            MigrationOp::CreateEnumType {
                type_name: "status".into(),
                labels: vec!["a".into()],
            },
            MigrationOp::DropEnumType {
                type_name: "status".into(),
            },
        ];
        for op in &ops {
            for dialect in DIALECTS {
                for direction in DIRECTIONS {
                    assert_eq!(
                        needs_for(op, &author(vec![]), &author(vec![]), dialect, direction),
                        Needs::Native,
                        "{op:?} {dialect:?} {direction:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn adding_a_column_by_shape_dialect_and_direction() {
        let before = author(vec![]);
        // (column, dialect, direction) → needs
        let cases: Vec<(SchemaColumn, bool, Dialect, PlanDirection, Needs)> = vec![
            // A1: an optional column, both dialects, both directions.
            (
                nullable("bio", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("bio", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("bio", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A1 with a foreign key: SQLite takes an inline REFERENCES.
            (
                nullable("team_id", "integer"),
                true,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                nullable("team_id", "integer"),
                true,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            // A2: a literal default backfills existing rows.
            (
                defaulted("tier"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                defaulted("tier"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                defaulted("tier"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A required FK column with a default: no REFERENCES on SQLite.
            (
                SchemaColumn {
                    default: Some(serde_json::json!(1)),
                    ..column("team_id", "integer")
                },
                true,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Rebuild,
            ),
            // A3: required, no default — a backfill going up, everywhere.
            (
                column("slug", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            (
                column("slug", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            // A down putting back a dropped NOT NULL column: Postgres adds it
            // and sets NOT NULL; SQLite needs a rebuild.
            (
                column("slug", "string"),
                false,
                Dialect::Postgres,
                PlanDirection::Down,
                Needs::Native,
            ),
            (
                column("slug", "string"),
                false,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Rebuild,
            ),
            // A null default is no default.
            (
                SchemaColumn {
                    default: Some(serde_json::Value::Null),
                    ..column("slug", "string")
                },
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            // A primary key added to an existing table.
            (
                SchemaColumn {
                    primary_key: true,
                    ..column("uid", "string")
                },
                false,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Refused(Refusal::PrimaryKeyChange),
            ),
        ];
        for (col, fk, dialect, direction, expected) in cases {
            let name = col.name.clone();
            let mut after = author(vec![col]);
            if fk {
                after = with_fk(after, &name);
            }
            assert_eq!(
                needs_for(&add(&name), &before, &after, dialect, direction),
                expected,
                "{name} {dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn dropping_a_column_by_shape_dialect_and_direction() {
        let after = author(vec![]);
        for dialect in DIALECTS {
            for direction in DIRECTIONS {
                // A4: a plain column, nullable or not.
                for col in [nullable("bio", "string"), column("bio", "string")] {
                    assert_eq!(
                        needs_for(&drop("bio"), &author(vec![col]), &after, dialect, direction),
                        Needs::Native
                    );
                }
                assert_eq!(
                    needs_for(
                        &drop("id"),
                        &author(vec![]),
                        &model("Author", vec![column("name", "string")]),
                        dialect,
                        direction
                    ),
                    Needs::Refused(Refusal::PrimaryKeyChange)
                );
            }
        }
        // C2: an FK column CREATE TABLE wrote. SQLite cannot drop it in place;
        // a down drops the inline REFERENCES column its up added.
        let before = with_fk(author(vec![nullable("team_id", "integer")]), "team_id");
        let expect = [
            (Dialect::Sqlite, PlanDirection::Up, Needs::Rebuild),
            (Dialect::Sqlite, PlanDirection::Down, Needs::Native),
            (Dialect::Postgres, PlanDirection::Up, Needs::Native),
            (Dialect::Postgres, PlanDirection::Down, Needs::Native),
        ];
        for (dialect, direction, needs) in expect {
            assert_eq!(
                needs_for(&drop("team_id"), &before, &after, dialect, direction),
                needs,
                "{dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn a_type_change_is_native_on_postgres_and_a_rebuild_on_sqlite() {
        let op = MigrationOp::AlterColumnType {
            table: "author".into(),
            column: "age".into(),
        };
        let before = author(vec![column("age", "integer")]);
        let after = author(vec![column("age", "string")]);
        for direction in DIRECTIONS {
            assert_eq!(
                needs_for(&op, &before, &after, Dialect::Postgres, direction),
                Needs::Native
            );
            assert_eq!(
                needs_for(&op, &before, &after, Dialect::Sqlite, direction),
                Needs::Rebuild
            );
        }
        // To or from a native enum type: the enum ticket's.
        let status = SchemaColumn {
            enum_values: Some(vec![serde_json::json!("a")]),
            enum_type_name: Some("status".into()),
            ..column("age", "string")
        };
        assert_eq!(
            needs_for(
                &op,
                &before,
                &author(vec![status]),
                Dialect::Postgres,
                PlanDirection::Up
            ),
            Needs::Refused(Refusal::Ticket(529))
        );
        // The primary key's type.
        let id_op = MigrationOp::AlterColumnType {
            table: "author".into(),
            column: "id".into(),
        };
        let uuid_pk = model(
            "Author",
            vec![
                SchemaColumn {
                    primary_key: true,
                    ..column("id", "uuid")
                },
                column("name", "string"),
            ],
        );
        for dialect in DIALECTS {
            assert_eq!(
                needs_for(
                    &id_op,
                    &author(vec![]),
                    &uuid_pk,
                    dialect,
                    PlanDirection::Up
                ),
                Needs::Refused(Refusal::PrimaryKeyChange)
            );
        }
    }

    #[test]
    fn relaxing_not_null_is_native_on_postgres_and_requiring_it_is_a_backfill() {
        let op = MigrationOp::AlterColumnNullability {
            table: "author".into(),
            column: "bio".into(),
        };
        let required = author(vec![column("bio", "string")]);
        let optional = author(vec![nullable("bio", "string")]);
        let cases = [
            // A7b, and its down's SET NOT NULL.
            (
                &required,
                &optional,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Native,
            ),
            (
                &optional,
                &required,
                Dialect::Postgres,
                PlanDirection::Down,
                Needs::Native,
            ),
            // A7a: values for the NULL rows first (ADR-0042).
            (
                &optional,
                &required,
                Dialect::Postgres,
                PlanDirection::Up,
                Needs::Backfill,
            ),
            (
                &required,
                &optional,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Rebuild,
            ),
            (
                &optional,
                &required,
                Dialect::Sqlite,
                PlanDirection::Down,
                Needs::Rebuild,
            ),
            (
                &optional,
                &required,
                Dialect::Sqlite,
                PlanDirection::Up,
                Needs::Rebuild,
            ),
        ];
        for (before, after, dialect, direction, expected) in cases {
            assert_eq!(
                needs_for(&op, before, after, dialect, direction),
                expected,
                "{dialect:?} {direction:?}"
            );
        }
    }

    #[test]
    fn indexes_are_native_on_sqlite_and_their_own_step_on_an_existing_postgres_table() {
        let index = SchemaIndex {
            name: "idx_author_name_bio".into(),
            columns: vec!["name".into(), "bio".into()],
            unique: false,
        };
        let plain = author(vec![nullable("bio", "string")]);
        let indexed = SchemaModel {
            indexes: vec![index],
            ..plain.clone()
        };
        let add = MigrationOp::AddIndex {
            table: "author".into(),
            name: "idx_author_name_bio".into(),
            columns: vec!["name".into(), "bio".into()],
            unique: false,
        };
        let drop_index = MigrationOp::DropIndex {
            table: "author".into(),
            name: "idx_author_name_bio".into(),
        };
        for direction in DIRECTIONS {
            assert_eq!(
                needs_for(&add, &plain, &indexed, Dialect::Sqlite, direction),
                Needs::Native
            );
            assert_eq!(
                needs_for(&drop_index, &indexed, &plain, Dialect::Sqlite, direction),
                Needs::Native
            );
            assert_eq!(
                needs_for(&add, &plain, &indexed, Dialect::Postgres, direction),
                Needs::Refused(Refusal::Ticket(527))
            );
            assert_eq!(
                needs_for(&drop_index, &indexed, &plain, Dialect::Postgres, direction),
                Needs::Refused(Refusal::Ticket(527))
            );
        }
        // On a table the same file creates or drops, the index rides the
        // table's own statement on every dialect.
        let (empty, with) = (ir(vec![]), ir(vec![indexed.clone()]));
        for dialect in DIALECTS {
            let created = PlanContext::of(&add, &empty, &with, dialect, PlanDirection::Up);
            assert!(!created.table_exists_before && created.table_exists_after);
            assert_eq!(assign(&add, &created).needs, Needs::Native);
            let dropped = PlanContext::of(&drop_index, &with, &empty, dialect, PlanDirection::Up);
            assert!(dropped.table_exists_before && !dropped.table_exists_after);
            assert_eq!(assign(&drop_index, &dropped).needs, Needs::Native);
        }
        // An index over a column the same file drops goes with the column.
        let without_bio = author(vec![]);
        let ctx_ir = (ir(vec![indexed.clone()]), ir(vec![without_bio]));
        let ctx = PlanContext::of(
            &drop_index,
            &ctx_ir.0,
            &ctx_ir.1,
            Dialect::Postgres,
            PlanDirection::Up,
        );
        assert!(goes_with_a_dropped_column(&drop_index, &ctx));
        assert_eq!(assign(&drop_index, &ctx).needs, Needs::Native);
        assert!(!carried_by_its_column_drop(&drop_index, &ctx));
    }

    #[test]
    fn a_dropped_columns_own_check_goes_with_it_and_any_other_check_change_is_staged() {
        let check = SchemaCheck {
            name: "ck_author_tier".into(),
            column: "tier".into(),
            values: vec!["'free'".into()],
        };
        let checked = SchemaModel {
            checks: vec![check],
            ..author(vec![nullable("tier", "string")])
        };
        let drop_check = MigrationOp::DropCheck {
            table: "author".into(),
            name: "ck_author_tier".into(),
        };
        let (before, gone) = (ir(vec![checked.clone()]), ir(vec![author(vec![])]));
        for dialect in DIALECTS {
            let ctx = PlanContext::of(&drop_check, &before, &gone, dialect, PlanDirection::Up);
            assert_eq!(assign(&drop_check, &ctx).needs, Needs::Native);
            assert_eq!(
                carried_by_its_column_drop(&drop_check, &ctx),
                dialect == Dialect::Sqlite
            );
        }
        // The column stays and only its check goes: an A10 drop.
        let unchecked = author(vec![nullable("tier", "string")]);
        assert_eq!(
            needs_for(
                &drop_check,
                &checked,
                &unchecked,
                Dialect::Sqlite,
                PlanDirection::Up
            ),
            Needs::Rebuild
        );
        assert_eq!(
            needs_for(
                &drop_check,
                &checked,
                &unchecked,
                Dialect::Postgres,
                PlanDirection::Up
            ),
            Needs::Refused(Refusal::Ticket(527))
        );
        let staged = [
            MigrationOp::AddCheck {
                table: "author".into(),
                name: "ck_author_tier".into(),
            },
            MigrationOp::RebuildCheck {
                table: "author".into(),
                name: "ck_author_tier".into(),
            },
            MigrationOp::AddForeignKey {
                table: "author".into(),
                column: "tier".into(),
            },
            MigrationOp::RebuildForeignKey {
                table: "author".into(),
                column: "tier".into(),
                old_name: "fk".into(),
            },
        ];
        for op in &staged {
            for direction in DIRECTIONS {
                assert_eq!(
                    needs_for(op, &checked, &checked, Dialect::Sqlite, direction),
                    Needs::Rebuild
                );
                assert_eq!(
                    needs_for(op, &checked, &checked, Dialect::Postgres, direction),
                    Needs::Refused(Refusal::Ticket(527))
                );
            }
        }
    }

    #[test]
    fn labels_row_security_and_live_only_ops_are_refused_naming_their_owner() {
        let a = author(vec![]);
        let table = || "author".to_string();
        let cases = [
            (
                MigrationOp::AddEnumLabel {
                    type_name: "status".into(),
                    label: "x".into(),
                },
                Refusal::Ticket(529),
            ),
            (
                MigrationOp::AddRowPolicy {
                    table: table(),
                    name: "p".into(),
                },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::RebuildRowPolicy {
                    table: table(),
                    name: "p".into(),
                },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::DropRowPolicy {
                    table: table(),
                    name: "p".into(),
                },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::EnableRowSecurity { table: table() },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::ForceRowSecurity { table: table() },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::DisableRowSecurity { table: table() },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::NoForceRowSecurity { table: table() },
                Refusal::Ticket(531),
            ),
            (
                MigrationOp::ValidateConstraint {
                    table: table(),
                    name: "ck".into(),
                },
                Refusal::LiveOnly,
            ),
            (
                MigrationOp::RebuildIndex {
                    table: table(),
                    name: "idx".into(),
                    columns: vec![],
                    unique: false,
                },
                Refusal::LiveOnly,
            ),
        ];
        for (op, refusal) in cases {
            for dialect in DIALECTS {
                for direction in DIRECTIONS {
                    assert_eq!(
                        needs_for(&op, &a, &a, dialect, direction),
                        Needs::Refused(refusal.clone()),
                        "{op:?}"
                    );
                }
            }
        }
    }

    #[test]
    fn a_primary_key_moving_between_columns_is_read_off_the_snapshots() {
        let before = ir(vec![author(vec![])]);
        assert_eq!(primary_key_change(&before, &before), None);
        let moved = model(
            "Author",
            vec![
                SchemaColumn {
                    primary_key: false,
                    ..pk()
                },
                SchemaColumn {
                    primary_key: true,
                    ..column("name", "string")
                },
            ],
        );
        assert_eq!(
            primary_key_change(&before, &ir(vec![moved])),
            Some("author".to_string())
        );
        // A table only one side has is a new or dropped model, not a key change.
        assert_eq!(primary_key_change(&before, &ir(vec![])), None);
    }
}
