def register_model_schema(name: str, schema: str) -> None: ...
async def connect(url: str, auto_migrate: bool = False) -> None: ...
async def create_tables() -> None: ...
async def fetch_all(cls: object) -> list[Any]: ...
async def fetch_filtered(cls: object, query_json: str) -> list[Any]: ...
async def count_filtered(name: str, query_json: str) -> int: ...
async def fetch_one(cls: object, pk_val: str) -> Any | None: ...
async def save_record(name: str, data: str) -> int | None: ...
async def save_bulk_records(name: str, data_list_json: str) -> int: ...
async def delete_record(name: str, pk_val: str) -> bool: ...
async def delete_filtered(name: str, query_json: str) -> int: ...
async def update_filtered(name: str, query_json: str, update_json: str) -> int: ...
async def begin_transaction() -> str: ...
async def commit_transaction(tx_id: str) -> None: ...
async def rollback_transaction(tx_id: str) -> None: ...
def register_instance(name: str, pk: str, obj: object) -> None: ...
def evict_instance(name: str, pk: str) -> None: ...
def reset_engine() -> None: ...
def clear_registry() -> None: ...
def version() -> str: ...
