def register_model_schema(name: str, schema: str) -> None: ...
async def connect(url: str, auto_migrate: bool = False) -> None: ...
async def create_tables() -> None: ...
async def fetch_all(cls: object) -> list[Any]: ...
async def fetch_one(cls: object, pk_val: str) -> Any | None: ...
async def save_record(name: str, data: str) -> None: ...
def register_instance(name: str, pk: str, obj: object) -> None: ...
def reset_engine() -> None: ...
def clear_registry() -> None: ...
def version() -> str: ...
